a1:
  env:
    num_actions: 12
    env_spacing: 3.  # not used with heightfields/trimeshes 
    episode_length_s: 4 # episode length in seconds

  terrain:
    mesh_type: 'plane'
    measure_heights: False
    # mesh_type: 'trimesh' # "heightfield" # none, plane, heightfield or trimesh
    # horizontal_scale: 0.1 # [m]
    # vertical_scale: 0.005 # [m]
    # border_size: 25 # [m]
    # curriculum: True
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.
    # # rough terrain only:
    # measure_heights: True
    measured_points_x: [-0.8       , -0.77460317, -0.74920635, -0.72380952, -0.6984127 , -0.67301587, -0.64761905, -0.62222222, -0.5968254 , -0.57142857, -0.54603175, -0.52063492, -0.4952381 , -0.46984127, -0.44444444, -0.41904762, -0.39365079, -0.36825397, -0.34285714, -0.31746032, -0.29206349, -0.26666667, -0.24126984, -0.21587302, -0.19047619, -0.16507937, -0.13968254, -0.11428571, -0.08888889, -0.06349206, -0.03809524, -0.01269841,  0.01269841,  0.03809524,  0.06349206,  0.08888889,  0.11428571,  0.13968254,  0.16507937,  0.19047619,  0.21587302,  0.24126984,  0.26666667,  0.29206349,  0.31746032,  0.34285714,  0.36825397,  0.39365079,  0.41904762,  0.44444444,  0.46984127,  0.4952381 ,  0.52063492,  0.54603175,  0.57142857,  0.5968254 ,  0.62222222,  0.64761905,  0.67301587,  0.6984127 ,  0.72380952,  0.74920635,  0.77460317,  0.8] # 1mx1.6m rectangle (without center line)
    measured_points_y: [-0.5       , -0.48412698, -0.46825397, -0.45238095, -0.43650794, -0.42063492, -0.4047619 , -0.38888889, -0.37301587, -0.35714286, -0.34126984, -0.32539683, -0.30952381, -0.29365079, -0.27777778, -0.26190476, -0.24603175, -0.23015873, -0.21428571, -0.1984127 , -0.18253968, -0.16666667, -0.15079365, -0.13492063, -0.11904762, -0.1031746 , -0.08730159, -0.07142857, -0.05555556, -0.03968254, -0.02380952, -0.00793651,  0.00793651,  0.02380952,  0.03968254,  0.05555556,  0.07142857,  0.08730159,  0.1031746 ,  0.11904762,  0.13492063,  0.15079365,  0.16666667,  0.18253968,  0.1984127 ,  0.21428571,  0.23015873,  0.24603175,  0.26190476,  0.27777778,  0.29365079,  0.30952381,  0.32539683,  0.34126984,  0.35714286,  0.37301587,  0.38888889,  0.4047619 ,  0.42063492,  0.43650794,  0.45238095,  0.46825397,  0.48412698,  0.5]
    # selected: False # select a unique terrain type and pass all arguments
    # terrain_kwargs: null # Dict of arguments for selected terrain
    # max_init_terrain_level: 5 # starting curriculum state
    # terrain_length: 8.
    # terrain_width: 8.
    # num_rows: 10 # number of terrain rows (levels)
    # num_cols: 20 # number of terrain cols (types)
    # # terrain types: [smooth slope, rough slope, stairs up, stairs down, discrete]
    # terrain_proportions: [0.1, 0.1, 0.35, 0.25, 0.2]
    # # trimesh only:
    # slope_treshold: 0.75 # slopes above this threshold will be corrected to vertical surfaces

  commands:
    curriculum: False
    max_curriculum: 1.
    num_commands: 4 # default: lin_vel_x, lin_vel_y, ang_vel_yaw, heading (in heading mode ang_vel_yaw is recomputed from heading error)
    resampling_time: 10. # time before command are changed[s]
    heading_command: False # if true: compute ang vel command from heading error

    ranges: {lin_vel_x: [-1.0, 1.0], lin_vel_y: [-1.0, 1.0], ang_vel_yaw: [-1, 1], heading: [-3.14, 3.14]}

  depth:
    capture_images: False
    original: [64, 64]
    horizontal_fov: 90
    # horizontal_fov_delta: 3

  init_state:
    pos: [0.0, 0.0, 0.42] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: { # = target angles [rad] when action = 0.0
        FL_hip_joint: 0.0,   # [rad]
        RL_hip_joint: 0.0,   # [rad]
        FR_hip_joint: 0.0,  # [rad]
        RR_hip_joint: 0.0,   # [rad]

        FL_thigh_joint: 0.9393,     # [rad]
        RL_thigh_joint: 0.9393,   # [rad]
        FR_thigh_joint: 0.9393,     # [rad]
        RR_thigh_joint: 0.9393,   # [rad]

        FL_calf_joint: -1.6462,   # [rad]
        RL_calf_joint: -1.6462,    # [rad]
        FR_calf_joint: -1.6462,  # [rad]
        RR_calf_joint: -1.6462,    # [rad]
    }
    motor_used: { # = target angles [rad] when action = 0.0
        FL_hip_joint: [0.01, 0.99],   # [rad]
        RL_hip_joint: [0.01, 0.99],   # [rad]
        FR_hip_joint: [0.01, 0.99],  # [rad]
        RR_hip_joint: [0.01, 0.99],   # [rad]

        FL_thigh_joint: [0.01, 0.90],     # [rad]
        RL_thigh_joint: [0.01, 0.90],   # [rad]
        FR_thigh_joint: [0.01, 0.90],     # [rad]
        RR_thigh_joint: [0.01, 0.90],   # [rad]

        FL_calf_joint: [0.01, 0.60],   # [rad]
        RL_calf_joint: [0.01, 0.60],    # [rad]
        FR_calf_joint: [0.01, 0.60],  # [rad]
        RR_calf_joint: [0.01, 0.60],    # [rad]
    }



  control:
    control_type: 'P' # P: position, V: velocity, T: torques
    # PD Drive parameters:
    stiffness: {joint: 100.}  # [N*m/rad]
    damping: {joint: 1.}     # [N*m*s/rad]

  asset:
    file: '{ASSET_PATH}/a1/urdf/a1.urdf'
    name: "a1"  # actor name
    foot_name: "foot" # name of the feet bodies, used to index body state and contact force tensors
    penalize_contacts_on: ["thigh", "calf"]
    terminate_after_contacts_on: ["base"]
    disable_gravity: False
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    fix_base_link: False # fixe the base of the robot
    default_dof_drive_mode: 3 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)
    self_collisions: 1 # 1 to disable, 0 to enable...bitwise filter
    replace_cylinder_with_capsule: True # replace collision cylinders with capsules, leads to faster/more stable simulation
    flip_visual_attachments: True # Some .obj meshes must be flipped from y-up to z-up
    
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    armature: 0.
    thickness: 0.01

  domain_rand:
    randomize_friction: False
    friction_range: [0.5, 1.25]
    randomize_base_mass: False
    added_mass_range: [-1., 1.]
    push_robots: False
    push_interval_s: 15
    max_push_vel_xy: 1.

  rewards:
    scales:
      dof_pos_limits: 0. # -10.0
      termination: -0.0
      tracking_lin_vel: 0. # 1. # 1.0
      tracking_ang_vel: 0. # 1. # 0.5
      lin_vel_z: 0. # -2.0
      ang_vel_xy: 0. # -0.05
      orientation: -0.
      torques: 0. # -0.00002
      dof_vel: -0.
      dof_acc:  0. # -2.5e-7
      base_height: 0. # 0.2
      feet_air_time: 0. # 1.0
      collision: 0. # -1.
      feet_stumble: -0.0 
      action_rate: 0. # -0.01
      daydreamer: 1.0
      stand_still: -0.
      upright: 0. # 0.2 

    only_positive_rewards: False # if true negative total rewards are clipped at zero (avoids early termination problems)
    tracking_sigma: 0.25 # tracking reward: exp(-error^2/sigma)
    base_height_sigma: 0.25
    soft_dof_pos_limit: 0.9 # percentage of urdf limits, values above this limit are penalized
    soft_dof_vel_limit: 1.
    soft_torque_limit: 1.
    base_height_target: 0.25
    max_contact_force: 100. # forces above this value are penalized

  normalization:
    obs_scales:
      lin_vel: 1.0 
      ang_vel: 1.0 
      dof_pos: 1.0
      dof_vel: 1.0
      height_measurements: 1.0
    clip_observations: 100.
    clip_actions: 100.

  noise:
    add_noise: False
    noise_level: 1.0 # scales other values
    noise_scales:
      dof_pos: 0.01
      dof_vel: 1.5
      lin_vel: 0.1
      ang_vel: 0.2
      gravity: 0.05
      height_measurements: 0.1

  # viewer camera:
  viewer:
    ref_env: 0
    pos: [10, 0, 6]  # [m]
    lookat: [11., 5., 3.]  # [m]

  sim:
    dt:  0.005
    substeps: 1
    gravity: [0., 0. ,-9.81]  # [m/s^2]
    up_axis: 1  # 0 is y, 1 is z

    physx:
      num_threads: 10
      solver_type: 1  # 0: pgs, 1: tgs
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.01  # [m]
      rest_offset: 0.0   # [m]
      bounce_threshold_velocity: 0.5 #0.5 [m/s]
      max_depenetration_velocity: 1.0
      max_gpu_contact_pairs: 8388608 #2**24 -> needed for 8000 envs and more
      default_buffer_size_multiplier: 5
      contact_collection: 2 # 0: never, 1: last sub-step, 2: all sub-steps (default=2)