defaults:

  # Trainer
  logdir: /dev/null
  seed: 0
  task: dummy_continuous
  run: train_eval
  env: {amount: 1, parallel: 'none', repeat: 1, size: [64, 64], camera: -1, gray: False, length: 0}
  replay: {capacity: 2e6, length: 50, ongoing: False, prioritize_ends: True, parallel: True}
  tf: {jit: True, platform: gpu, precision: 16}
  train:
    steps: 1e8
    expl_until: 0
    log_every: 1e4
    eval_every: 1e5
    eval_eps: 1
    train_every: 5
    train_steps: 1
    prefill: 10000
    pretrain: 0
    log_keys_video: ['image']
    log_keys_sum: '^$'
    log_keys_mean: '^$'
    log_keys_max: '^$'
    log_timings: True

  # Agent
  batch_size: 16
  clip_rewards: tanh
  expl_behavior: greedy
  expl_noise: 0.0
  eval_noise: 0.0
  eval_state_mean: False
  data_loaders: 16

  # World Model
  grad_heads: [decoder, reward, discount]
  pred_discount: True
  rssm: {ensemble: 1, hidden: 1024, deter: 1024, stoch: 32, discrete: 32, act: elu, norm: none, std_act: sigmoid2, min_std: 0.1}
  encoder: {mlp_keys: '.*', cnn_keys: '.*', act: elu, norm: none, cnn_depth: 48, cnn_kernels: [4, 4, 4, 4], mlp_layers: 4, mlp_units: 400}
  decoder: {mlp_keys: '.*', cnn_keys: '.*', act: elu, norm: none, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: 4, mlp_units: 400}
  reward_head: {layers: 4, units: 400, act: elu, norm: none, dist: mse}
  discount_head: {layers: 4, units: 400, act: elu, norm: none, dist: binary}
  loss_scales: {kl: 1.0, reward: 1.0, discount: 1.0}
  kl: {free: 0.0, forward: False, balance: 0.8, free_avg: True}
  model_opt: {opt: adam, lr: 1e-4, eps: 1e-5, clip: 100.0, wd: 1e-6}

  # Actor Critic
  actor: {layers: 4, units: 400, act: elu, norm: none, dist: auto, min_std: 0.1}
  critic: {layers: 4, units: 400, act: elu, norm: none, dist: mse}
  actor_opt: {opt: adam, lr: 8e-5, eps: 1e-5, clip: 100.0, wd: 1e-6}
  critic_opt: {opt: adam, lr: 2e-4, eps: 1e-5, clip: 100.0, wd: 1e-6}
  discount: 0.99
  discount_lambda: 0.95
  imag_horizon: 15
  imag_unroll: True
  actor_grad: auto
  actor_grad_mix: 0.1
  actor_ent: 2e-3
  slow_target: True
  slow_target_update: 100
  slow_target_fraction: 1.0
  slow_baseline: True
  reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}

  # Exploration
  expl_intr_scale: 1.0
  expl_extr_scale: 0.0
  expl_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100.0, wd: 1e-6}
  expl_head: {layers: 4, units: 400, act: elu, norm: none, dist: mse}
  expl_reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}
  disag_target: stoch
  disag_log: False
  disag_models: 10
  disag_offset: 1
  disag_action_cond: True
  expl_model_loss: kl

nonepisodic: &nonepisodic

  pred_discount: False
  replay.prioritize_ends: False
  grad_heads: [decoder, reward]

atari:

  task: atari_pong
  env: {gray: True, repeat: 4}
  train.steps: 5e7
  train.eval_every: 2.5e5
  train.prefill: 50000
  train.train_every: 16
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}
  clip_rewards: tanh
  rssm: {hidden: 600, deter: 600}
  model_opt.lr: 2e-4
  actor_opt.lr: 4e-5
  critic_opt.lr: 1e-4
  actor_ent: 1e-3
  discount: 0.999
  loss_scales.kl: 0.1
  loss_scales.discount: 5.0

crafter:

  task: crafter_reward
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}
  train.log_keys_max: '^log_achievement_.*'
  train.log_keys_sum: '^log_reward$'
  discount: 0.999
  .*\.norm: layer

dmc_vision:

  <<: *nonepisodic
  task: dmc_walker_walk
  env.repeat: 2
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}
  train.eval_every: 1e4
  train.prefill: 1000
  train.pretrain: 100
  clip_rewards: identity
  rssm: {hidden: 200, deter: 200}
  model_opt.lr: 3e-4
  actor_opt.lr: 8e-5
  critic_opt.lr: 8e-5
  actor_ent: 1e-4
  kl.free: 1.0

dmc_proprio:

  <<: *nonepisodic
  task: dmc_walker_walk
  env.repeat: 2
  encoder: {mlp_keys: '.*', cnn_keys: '$^'}
  decoder: {mlp_keys: '.*', cnn_keys: '$^'}
  train.eval_every: 1e4
  train.prefill: 1000
  train.pretrain: 100
  clip_rewards: identity
  rssm: {hidden: 200, deter: 200}
  model_opt.lr: 3e-4
  actor_opt.lr: 8e-5
  critic_opt.lr: 8e-5
  actor_ent: 1e-4
  kl.free: 1.0

debug:
  env.length: 100
  train:
    eval_every: 300
    log_every: 300
    prefill: 100
    train_steps: 1
    train_every: 30
  batch_size: 4
  replay.length: 8
  encoder.cnn_depth: 16
  decoder.cnn_depth: 16
  rssm: {deter: 64, hidden: 64, stoch: 8, discrete: 8}
  .*\.layers: 2
  .*\.units: 64
  tf.jit: False
